parameters:
#    afpacalculette.example.class: afpa\calculetteBundle\Example

services:
#    afpacalculette.example:
#        class: %afpacalculette.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
